import esbuild from "esbuild";
import fs from "fs";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin repository.
*/`;

const production = process.argv[2] === "production";
const stylesSource = "src/styles/plugin.css";
const stylesDest = "styles.css";

const copyStyles = () => {
  if (!fs.existsSync(stylesSource)) {
    console.warn(`⚠️  Styles source not found: ${stylesSource}`);
    return;
  }
  try {
    fs.copyFileSync(stylesSource, stylesDest);
    console.log("🎨 Copied plugin styles to styles.css");
  } catch (err) {
    console.error("❌ Failed to copy styles:", err);
  }
};

let stylesWatcher;
const watchStyles = () => {
  if (stylesWatcher || !fs.existsSync(stylesSource)) {
    return;
  }
  stylesWatcher = fs.watch(stylesSource, () => {
    copyStyles();
  });
};

/** @type {esbuild.BuildOptions} */
const baseConfig = {

  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "child_process",
    "fs",
    "path"
  ],
  format: "cjs",
  target: "es2020",
  platform: "browser",
  logLevel: "info",
  outfile: "main.js",
};

if (production) {
  esbuild
    .build(baseConfig)
    .then(() => {
      copyStyles();
    })
    .catch(() => process.exit(1));
} else {
  esbuild
    .context({
      ...baseConfig,
      sourcemap: "inline",
      watch: {
        onRebuild(error) {
          if (error) {
            console.error("❌ Rebuild failed:", error);
          } else {
            console.log("✅ Rebuild succeeded");
            copyStyles();
          }
        },
      },
    })
    .then((ctx) => {
      copyStyles();
      watchStyles();
      console.log("📦 Watching for changes...");
      return ctx.watch();
    })
    .catch(() => process.exit(1));
}


